apiVersion: v1
kind: Pod
metadata:
  name: basic
  labels:
    type: webserver
spec:
  containers:
  - name: webcnt
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: fdlogger
    image: fluentd
