apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox1
    resources: {}
    command: ["/bin/sleep"]
    args: ["3600"]
    volumeMounts:
    - name: myvol
      mountPath: /etc/foo
  - image: busybox
    name: busybox2
    resources: {}
    command: ["/bin/sleep"]
    args: ["3600"]
    volumeMounts:
    - name: myvol
      mountPath: /etc/foo
  dnsPolicy: ClusterFirst
  volumes:
  - name: myvol
    emptyDir: {}
